name: pkg-update

on:
  schedule:
    - cron: '0 0 * * *'
  push:
    branches:
      - actions/trigger/pkg-update

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        julia-version: [1.2.0]
        julia-arch: [x86]
        os: [ubuntu-latest]
    steps:
      - uses: julia-actions/setup-julia@latest
        with:
          version: ${{ matrix.julia-version }}

      - uses: actions/checkout@v2
      - name: '"Merge" master to create-pull-request/pkg-update'
        run: |
          git fetch --unshallow origin \
            refs/heads/master:refs/remotes/origin/master \
            refs/heads/create-pull-request/pkg-update:refs/remotes/origin/create-pull-request/pkg-update \
            || exit 0
          git config --global user.email "tkf@users.noreply.github.com"
          git config --global user.name "tkf"
          git checkout -B master origin/master
          git merge --strategy=ours origin/create-pull-request/pkg-update
          git checkout -B create-pull-request/pkg-update
          git branch --set-upstream-to origin/create-pull-request/pkg-update

      - name: Update test/Manifest.toml
        run: julia --project=test -e "import Pkg; Pkg.update()"
      - name: Update docs/Manifest.toml
        run: julia --project=docs -e "import Pkg; Pkg.update()"

      # https://github.com/marketplace/actions/create-pull-request
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: Update */Manifest.toml
          title: '[AUTO] Update */Manifest.toml'
          labels: no changelog
          branch: create-pull-request/pkg-update
          branch-suffix: none
          base: master
      - name: Check output environment variable
        run: echo "Pull Request Number - ${{ env.PULL_REQUEST_NUMBER }}"
