name: Run test via Pkg.test()

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  vanilla-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: curl --silent --dump-header - https://pkg.julialang.org/
      - uses: julia-actions/setup-julia@v1
        with:
          version: ^1
      - uses: julia-actions/julia-buildpkg@latest
      - uses: julia-actions/julia-runtest@latest
